edition: 1.0.0
name: fcDeployApp
access: myAlias

services:
  fc-deploy-test:
    component: fc
    props:
      region: cn-shanghai
      service:
        name: qianfeng-fc-deploy-service
        description: 'demo for fc-deploy component'
        internetAccess: true
        role:
          name: qianfeng-fc-deploy-role
          policies:
            - AliyunContainerRegistryReadOnlyAccess
      function:
        name: custom-container-function
        runtime: custom-container
        caPort: 8080
        codeUri: ./
        timeout: 60
        customContainerConfig:
          image: ${env(image)}
          command: '["node"]'
          args: '["server.js"]'
        environmentVariables:
          testEnv: true
      triggers:
        - name: httpTrigger
          type: http
          config:
            authType: anonymous
            methods:
              - GET
              - POST
              - PUT
      customDomains:
        - domainName: auto
          protocol: HTTP
          routeConfigs:
            - path: /*
              serviceName: qianfeng-fc-deploy-service
              functionName: custom-container-function
