export default {
  Code: 200,
  Status: 'Success',
  Body: [
    {
      name_zh: 'fc-runtime-starter - 快速部署一个 FC 函数',
      name_en: 'fc-runtime-starter - Deploy FC function in 5 minutes',
      value: 'fc-runtime-starter',
      templates: [
        {
          id: 1,
          name_zh: 'fc-http-nodejs - 快速部署一个 nodejs12 http函数',
          name_en: 'fc-http-nodejs - Deploy FC nodejs12 runtime http function',
          value: 'devsapp/start-fc-http-nodejs12',
          is_deploy: true,
          category_id: 1,
          created_time: '2021-10-03T11:06:34.473Z',
        },
        {
          id: 2,
          name_zh: 'fc-http-python - 快速部署一个 python3 http函数',
          name_en: 'fc-http-python - Deploy FC python3 runtime http function',
          value: 'devsapp/start-fc-http-python3',
          is_deploy: true,
          category_id: 1,
          created_time: '2021-10-03T12:36:26.450Z',
        },
        {
          id: 7,
          name_zh: 'fc-http-java - 快速部署一个 java8 http函数',
          name_en: 'fc-http-java - Deploy FC java8 runtime http function',
          value: 'devsapp/start-fc-http-java8',
          is_deploy: false,
          category_id: 1,
          created_time: '2021-10-12T06:29:59.392Z',
        },
        {
          id: 23,
          name_zh: 'fc-event-nodejs - 快速部署一个 nodejs12 event函数',
          name_en: 'fc-event-nodejs - Deploy FC nodejs12 runtime event function',
          value: 'devsapp/start-fc-event-nodejs12',
          is_deploy: true,
          category_id: 1,
          created_time: '2021-10-13T07:43:38.542Z',
        },
        {
          id: 24,
          name_zh: 'fc-event-python - 快速部署一个 python3 event函数',
          name_en: 'fc-event-python - Deploy FC python3 runtime event function',
          value: 'devsapp/start-fc-event-python3',
          is_deploy: true,
          category_id: 1,
          created_time: '2021-10-13T07:57:35.429Z',
        },
        {
          id: 25,
          name_zh: 'fc-http-php - 快速部署一个 php http函数',
          name_en: 'fc-http-php - Deploy FC php runtime http function',
          value: 'devsapp/start-fc-http-php7',
          is_deploy: true,
          category_id: 1,
          created_time: '2021-10-13T08:01:38.523Z',
        },
        {
          id: 26,
          name_zh: 'fc-event-php - 快速部署一个 php event函数',
          name_en: 'fc-event-php - Deploy FC php runtime event function',
          value: 'devsapp/start-fc-event-php7',
          is_deploy: true,
          category_id: 1,
          created_time: '2021-10-13T08:04:27.547Z',
        },
        {
          id: 27,
          name_zh: 'fc-event-java - 快速部署一个 java8 event函数',
          name_en: 'fc-event-java - Deploy FC java8 runtime event function',
          value: 'devsapp/start-fc-event-java8',
          is_deploy: false,
          category_id: 1,
          created_time: '2021-10-13T08:09:34.561Z',
        },
      ],
    },
    {
      name_zh: 'fc-custom-container-stater - 快速部署一个 custom-container 应用',
      name_en: 'fc-custom-container-stater - Deploy FC function with custom-container',
      value: 'fc-custom-container-stater',
      templates: [
        {
          id: 3,
          name_zh: 'fc-custom-container-event-python3 - 快速部署一个通过事件触发的 python3 应用',
          name_en: 'fc-custom-container-event-python3 - Deploy python3 event-triggered application',
          value: 'devsapp/start-fc-custom-container-event-python3.9',
          is_deploy: false,
          category_id: 4,
          created_time: '2021-10-12T06:23:10.797Z',
        },
        {
          id: 4,
          name_zh: 'fc-custom-container-event-cpp - 快速部署一个通过事件触发的 cpp 应用',
          name_en: 'fc-custom-container-event-cpp - Deploy cpp event-triggered application',
          value: 'devsapp/start-fc-custom-container-event-cpp',
          is_deploy: false,
          category_id: 4,
          created_time: '2021-10-12T06:25:15.558Z',
        },
        {
          id: 5,
          name_zh: 'fc-custom-container-http-springboot - 快速部署一个通过 HTTP 请求触发的 springboot 应用',
          name_en: 'fc-custom-container-http-springboot - Deploy springboot HTTP Request-triggered application',
          value: 'devsapp/start-fc-custom-container-http-springboot',
          is_deploy: false,
          category_id: 4,
          created_time: '2021-10-12T06:26:38.646Z',
        },
        {
          id: 6,
          name_zh: 'fc-custom-container-http-aspdotnetcore - 快速部署一个通过 HTTP 请求触发的 aspdotnetcore 应用',
          name_en: 'fc-custom-container-http-aspdotnetcore - Deploy dotnetcore HTTP Request-triggered application',
          value: 'devsapp/start-fc-custom-container-http-aspdotnetcore',
          is_deploy: false,
          category_id: 4,
          created_time: '2021-10-12T06:27:57.306Z',
        },
      ],
    },
    {
      name_zh: 'web-framework-stater - 快速部署一个 Web 框架',
      name_en: 'web-framework-stater-Quickly deploy a web framework',
      value: 'web',
      templates: [
        {
          id: 8,
          name_zh: 'express-starter - 快速部署一个 express 基础应用',
          name_en: 'express-starter - Deploy express application',
          value: 'devsapp/start-express',
          is_deploy: false,
          category_id: 5,
          created_time: '2021-10-12T06:42:50.811Z',
        },
        {
          id: 9,
          name_zh: 'koa-starter - 快速部署一个 koa 基础应用',
          name_en: 'koa-starter - Deploy koa application',
          value: 'devsapp/start-koa',
          is_deploy: true,
          category_id: 5,
          created_time: '2021-10-12T06:44:17.038Z',
        },
        {
          id: 10,
          name_zh: 'nuxtjs-starter - 快速部署一个 nuxtjs 基础应用',
          name_en: 'nuxtjs-starter - Deploy nuxtjs application',
          value: 'devsapp/start-nuxt',
          is_deploy: true,
          category_id: 5,
          created_time: '2021-10-12T06:45:11.491Z',
        },
        {
          id: 11,
          name_zh: 'eggjs-starter - 快速部署一个 eggjs 基础应用',
          name_en: 'eggjs-starter - Deploy eggjs application',
          value: 'devsapp/start-egg',
          is_deploy: true,
          category_id: 5,
          created_time: '2021-10-12T06:51:54.762Z',
        },
        {
          id: 12,
          name_zh: 'flask-starter - 快速部署一个 flask 基础应用',
          name_en: 'flask-starter - Deploy flask application',
          value: 'devsapp/start-flask',
          is_deploy: false,
          category_id: 5,
          created_time: '2021-10-12T06:52:38.428Z',
        },
        {
          id: 13,
          name_zh: 'SpringBoot-starter - 快速部署一个 SpringBoot 基础应用',
          name_en: 'SpringBoot-starter - Deploy SpringBoot application',
          value: 'devsapp/start-springboot',
          is_deploy: false,
          category_id: 5,
          created_time: '2021-10-12T06:55:44.149Z',
        },
        {
          id: 14,
          name_zh: 'Zblog-starter - 快速部署一个 Zblog 基础应用',
          name_en: 'Zblog-starter - Deploy Zblog application',
          value: 'devsapp/start-zblog',
          is_deploy: false,
          category_id: 5,
          created_time: '2021-10-12T06:56:32.239Z',
        },
      ],
    },
    {
      name_zh: 'static-website-stater - 快速部署一个静态网站',
      name_en: 'static-website-stater-Quickly deploy a static website',
      value: 'static-site',
      templates: [
        {
          id: 15,
          name_zh: 'website-starter - 快速部署一个静态网站',
          name_en: 'website-starter - Deploy static website',
          value: 'devsapp/website-base',
          is_deploy: true,
          category_id: 6,
          created_time: '2021-10-12T07:15:48.795Z',
        },
        {
          id: 16,
          name_zh: 'react-starter - 快速部署一个 React.js 应用',
          name_en: 'react-starter - Deploy React.js application',
          value: 'devsapp/website-react',
          is_deploy: true,
          category_id: 6,
          created_time: '2021-10-12T07:16:39.534Z',
        },
        {
          id: 17,
          name_zh: 'vue-starter - 快速部署一个 Vue.js 应用',
          name_en: 'vue-starter - Deploy Vue.js application',
          value: 'devsapp/website-vue',
          is_deploy: true,
          category_id: 6,
          created_time: '2021-10-12T07:17:17.360Z',
        },
      ],
    },
    {
      name_zh: 'serverless-best-practice - 快速体验 Serverless 最佳实践',
      name_en: 'serverless-best-practice-Quickly experience serverless best practices',
      value: 'best-practice',
      templates: [
        {
          id: 18,
          name_zh: 'puppeteer - 快速部署一个基于 puppeteer 截图的 Web 应用',
          name_en: 'puppeteer - Deploy screenshot application base on puppeteer + fc',
          value: 'devsapp/puppeteer-app',
          is_deploy: false,
          category_id: 7,
          created_time: '2021-10-12T07:17:59.874Z',
        },
        {
          id: 19,
          name_zh: 'ffmpeg - 快速部署一个基于 ffmpeg 实现音视频处理应用',
          name_en: 'ffmpeg - Deploy audio and video processing application base on ffmpeg + fc',
          value: 'devsapp/ffmpeg-app',
          is_deploy: false,
          category_id: 7,
          created_time: '2021-10-12T07:18:40.591Z',
        },
        {
          id: 20,
          name_zh: 'pdf2Img - 快速部署一个 pdf 转图片应用',
          name_en: 'pdf2Img - Deploy pdf to images application',
          value: 'devsapp/start-pdf2img',
          is_deploy: false,
          category_id: 7,
          created_time: '2021-10-12T07:19:25.791Z',
        },
        {
          id: 21,
          name_zh: 'tensorflow - 快速部署一个 tensorflow 应用',
          name_en: 'tensorflow - Deploy tensorflow application',
          value: 'devsapp/start-tensorflow',
          is_deploy: false,
          category_id: 7,
          created_time: '2021-10-12T07:20:07.140Z',
        },
        {
          id: 22,
          name_zh: 'todoList - 快速部署一个基于 nodejs 的网页 TodoList 应用',
          name_en: 'todoList - Deploy todoList application',
          value: 'devsapp/todolist-app',
          is_deploy: false,
          category_id: 7,
          created_time: '2021-10-12T07:20:44.323Z',
        },
      ],
    },
  ],
};
