name: release-assets

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      - name: Install
        run: npm install
      - name: pkg
        run: npm run pkg
      - name: Zip the macos
        run: |
          mv s-macos s-${{ github.ref_name }}-macos
          zip -r s-${{ github.ref_name }}-macos.zip s-${{ github.ref_name }}-macos
      - name: Zip the linux
        run: |
          mv s-linux s-${{ github.ref_name }}-linux
          zip -r s-${{ github.ref_name }}-linux.zip s-${{ github.ref_name }}-linux
      - name: Zip the windows
        run: |
          mv s-win.exe s-${{ github.ref_name }}-win.exe
          zip -r s-${{ github.ref_name }}-win.exe.zip s-${{ github.ref_name }}-win.exe
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          token: ${{ secrets.CUSTOM_GITHUB_TOKEN }}
          files: |
            s-${{ github.ref_name }}-macos.zip
            s-${{ github.ref_name }}-linux.zip
            s-${{ github.ref_name }}-win.exe.zip
