name: release-assets

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      - name: Install
        run: npm install
      - name: pkg
        run: npm run pkg
      - name: Zip the macos
        run: |
          zip -r serverless-devs-${{ github.ref_name }}-macos.zip ./pkg/macos
      - name: Zip the linux
        run: |
          zip -r serverless-devs-${{ github.ref_name }}-linux.zip ./pkg/linux
      - name: Zip the windows
        run: |
          zip -r serverless-devs-${{ github.ref_name }}-windows.zip ./pkg/windows
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          token: ${{ secrets.CUSTOM_GITHUB_TOKEN }}
          files: |
            serverless-devs-${{ github.ref_name }}-macos.zip
            serverless-devs-${{ github.ref_name }}-linux.zip
            serverless-devs-${{ github.ref_name }}-windows.zip
